artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "masoudnickparvar/brain-tumor-mri-dataset"
  local_data_file: artifacts/data_ingestion/brain-mri
  unzip_dir: artifacts/data_ingestion/brain-mri/

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/brain_model.h5
